name: recipes_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  connectivity_plus: ^3.0.4
  dartz: ^0.10.1
  dio: ^5.1.1
  flex_color_scheme: ^7.0.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.1+1
  flutter_hooks: ^0.18.6
  font_awesome_flutter: ^10.4.0
  freezed_annotation: ^2.2.0
  go_router: ^6.5.6
  google_fonts: ^4.0.3
  hooks_riverpod: ^2.3.4
  http: ^0.13.5
  json_annotation: ^4.8.0
  riverpod_annotation: ^2.0.4
  shared_preferences: ^2.1.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  riverpod_generator: ^2.1.6

flutter:
  uses-material-design: true
